/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A1;

public class App {

    public static void main(String[] args) {
        // Welcome message
        System.out.println("============ A T M ============");
        System.out.println("      Welcome to XYZ Bank      ");
        System.out.println("===============================");

        // Initialize ATM System
        ATM atm = new ATM("0");

        // Take Card Number From User input
        String cardNum = atm.userCardNum();

        // Initialize Customer System
        Customer new_customer = atm.initCustomer(cardNum); // null if the Card Number is invalid

        //Exit if the card number of this customer is not valid.
        if(new_customer == null){
            System.out.println("Sorry, that card number is not valid.");
            System.exit(0);
        }
        // Validate the PIN from the input of customer.
        // Exit program while more than three attempts.
        boolean correctPIN = atm.validatePIN(new_customer);
        if (!correctPIN) {
            System.exit(0);
        }

        // If user is an admin, take user into the admin system then exit
        if(new_customer.isAdmin()){
            atm.runAdminSystem();
            System.exit(0);
        }

        // If customer is not an admin,take user into the standard user system
        else{atm.runStandardSystem(new_customer);}
    }
}
